language: python
sudo: required

python:
  - "3.4"
#  - "3.5"

# For instructions on installing OS dependencies, see:
# - https://docs.travis-ci.com/user/installing-dependencies/

services:
  - mysql

before_install:
  - mysql -u root -e 'CREATE DATABASE oldtests DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_bin;'
  - mysql -u root -e "CREATE USER 'old'@'localhost' IDENTIFIED BY 'demo';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON oldtests.* TO 'old'@'localhost';"

# command to install dependencies
install: "pip install -r requirements/test-oursql.txt -e \".[testing]\""

# command to run tests
script: pytest old/tests -v
